CB_PROFILE_STATS = 'profile:stats'
CB_PROFILE_STATS_REFRESH = 'profile:stats:refresh'
CB_PROFILE_EDIT = 'profile:edit'
CB_PROFILE_SETTINGS = 'profile:settings'
CB_PROFILE_NOTIFICATIONS = 'profile:notifications'
CB_PROFILE_LANGUAGE = 'profile:language'
CB_PROFILE_LAST_ACTIVITY = 'profile:last_activity'
CB_PROFILE_LAST_ACTIVITY_ENABLE = 'profile:last_activity:enable'
CB_PROFILE_LAST_ACTIVITY_DISABLE = 'profile:last_activity:disable'
CB_PROFILE_BACK = 'profile:back'

CB_PROFILE_NOTIF_LIKES = 'profile:notif:likes'
CB_PROFILE_NOTIF_SUBS = 'profile:notif:subs'
CB_PROFILE_NOTIF_MESSAGES = 'profile:notif:messages'

CB_PROFILE_EDIT_AVATAR = 'profile:edit:avatar'
CB_PROFILE_EDIT_FULL_NAME = 'profile:edit:full_name'
CB_PROFILE_EDIT_GENDER = 'profile:edit:gender'
CB_PROFILE_EDIT_USERNAME = 'profile:edit:username'
CB_PROFILE_EDIT_CANCEL = 'profile:edit:cancel'

CB_PROFILE_LANG_SET_PREFIX = 'profile:lang:set:'
CB_PROFILE_GENDER_SET_PREFIX = 'profile:gender:set:'

CB_MY_PROFILES_GAME_PREFIX = 'profiles:game:'
CB_MY_PROFILES_BACK = 'profiles:back'
CB_MY_PROFILES_CARD_BACK = 'profiles:card_back'
CB_MY_PROFILES_CREATE_MENU = 'profiles:create_menu'
CB_MY_PROFILES_CREATE_PICK_PREFIX = 'profiles:create_pick:'
CB_MY_PROFILES_CREATE_CANCEL = 'profiles:create_cancel'
CB_MY_PROFILES_EDIT = 'profiles:edit'
CB_MY_PROFILES_EDIT_CANCEL = 'profiles:edit_cancel'
CB_MY_PROFILES_HIDE_NOTICE = 'profiles:hide_notice'
CB_MY_PROFILES_EDIT_FIELD_PREFIX = 'profiles:edit_field:'
CB_MY_PROFILES_DELETE_ASK = 'profiles:delete_ask'
CB_MY_PROFILES_DELETE_CONFIRM = 'profiles:delete_confirm'
CB_MY_PROFILES_DELETE_CANCEL = 'profiles:delete_cancel'
CB_MY_PROFILES_REFILL = 'profiles:refill'

CB_MY_PROFILES_MLBB_MAIN_PREFIX = 'profiles:mlbb:main:'
CB_MY_PROFILES_MLBB_EXTRA_PREFIX = 'profiles:mlbb:extra:'
CB_MY_PROFILES_MLBB_EXTRA_DONE = 'profiles:mlbb:extra:done'
CB_MY_PROFILES_MLBB_RANK_PREFIX = 'profiles:mlbb:rank:'
CB_MY_PROFILES_MLBB_SERVER_PREFIX = 'profiles:mlbb:server:'
CB_MY_PROFILES_GENSHIN_REGION_PREFIX = 'profiles:genshin:region:'
CB_MY_PROFILES_PUBG_RANK_PREFIX = 'profiles:pubg:rank:'

CB_ADMIN_PROFILE_APPROVE_PREFIX = 'adm:ok:'
CB_ADMIN_PROFILE_DELETE_PREFIX = 'adm:del:'
CB_ADMIN_PROFILE_DELETE_REASON_PREFIX = 'adm:why:'
CB_ADMIN_PROFILE_REFRESH_PREFIX = 'adm:rf:'
CB_ADMIN_PROFILE_HIDE_PREFIX = 'adm:hd:'
CB_ADMIN_PANEL_STATS = 'adm:panel:stats'
CB_ADMIN_PANEL_REFRESH = 'adm:panel:refresh'
CB_ADMIN_PANEL_BACK = 'adm:panel:back'
CB_ADMIN_PANEL_HIDE = 'adm:panel:hide'

CB_SEARCH_GAME_PICK_PREFIX = 'search:pick:'
CB_SEARCH_CREATE_PROFILE = 'search:create_profile'
CB_SEARCH_BACK_MAIN = 'search:back_main'
CB_SEARCH_LIKE_PREFIX = 'search:like:'
CB_SEARCH_MESSAGE_PREFIX = 'search:message:'
CB_SEARCH_SUB_PREFIX = 'search:sub:'
CB_SEARCH_NEXT_PREFIX = 'search:next:'
CB_SEARCH_PREV_PREFIX = 'search:prev:'
CB_SEARCH_RETRY_PREFIX = 'search:retry:'
CB_SEARCH_VIEW_LIKER_PREFIX = 'search:view_liker:'
CB_SEARCH_VIEW_PROFILE_PREFIX = 'search:view_profile:'
CB_SEARCH_USER_PROFILES_PREFIX = 'search:user_profiles:'
CB_SEARCH_USER_PROFILE_GAME_PREFIX = 'search:user_profile_game:'
CB_SEARCH_BACK_TO_CARD = 'search:back_to_card'
CB_SEARCH_BACK_TO_PROFILE_PREFIX = 'search:back_to_profile:'
CB_SEARCH_HIDE_NOTICE = 'search:hide_notice'
CB_SEARCH_CANCEL_MESSAGE = 'search:cancel_message'

CB_ACTIVITY_OPEN = 'activity:open'
CB_ACTIVITY_SECTION_PREFIX = 'activity:section:'
CB_ACTIVITY_PAGE_PREFIX = 'activity:page:'
CB_ACTIVITY_REFRESH_PREFIX = 'activity:refresh:'
CB_ACTIVITY_BACK = 'activity:back'

CB_CHATS_OPEN = 'chats:open'
CB_CHATS_PAGE_PREFIX = 'chats:page:'
CB_CHATS_NEW = 'chats:new'
CB_CHATS_OPEN_CHAT_PREFIX = 'chats:chat:'
CB_CHATS_MESSAGES_PAGE_PREFIX = 'chats:msg:'
CB_CHATS_SEND_PREFIX = 'chats:send:'
CB_CHATS_MENU = 'chats:menu'
CB_CHATS_CANCEL_SEND_PREFIX = 'chats:cancel_send:'
CB_CHATS_CANCEL_NEW = 'chats:cancel_new'
CB_CHATS_DELETE_PREFIX = 'chats:delete:'
