PROFILE_IMAGE_FILE_ID = 'AgACAgIAAxkBAAIEFGnFaKLyRAUVRmxkJCaNqwxs--6UAAJGF2sbJ2kpSnzmZLjkR3g9AQADAgADeAADOgQ'
PROFILE_STATS_IMAGE_FILE_ID = 'AgACAgIAAxkBAAIEHWnFaaSUF3KrkbeP0sM-kA2CAVc8AAJSF2sbJ2kpSs58AUjeY44WAQADAgADeAADOgQ'
PROFILE_NOTIFICATIONS_IMAGE_FILE_ID = 'AgACAgIAAxkBAAIEH2nFaayS-yOgW-4q6uapDzS9HefAAAJTF2sbJ2kpSjXtCbfvZzXuAQADAgADeQADOgQ'
PROFILE_LANGUAGE_IMAGE_FILE_ID = 'AgACAgIAAxkBAAIEJWnFa_7F1L9avSCNhN-7YTuCk-ewAAJlF2sbJ2kpSu96FUTyqwEiAQADAgADeQADOgQ'
SEARCH_GAME_PICK_IMAGE_FILE_ID = 'AgACAgIAAxkBAAIEJ2nFbBEG2KEbmvAZBHnUyhmR_rkTAAJnF2sbJ2kpSjaONzADaff8AQADAgADeAADOgQ'
PROFILE_EDIT_IMAGE_FILE_ID = 'AgACAgIAAxkBAAIEKWnFbCKR3eCnc079lxzq7tqzATuwAAJoF2sbJ2kpSlaRI8oIYZHCAQADAgADeAADOgQ'
MY_PROFILES_IMAGE_FILE_ID = 'AgACAgIAAxkBAAIEK2nFbDM-8ZcGVVuUMPlTgmxONYv1AAJpF2sbJ2kpSs6cN0KXUPtRAQADAgADeQADOgQ'
MY_PROFILES_CREATE_IMAGE_FILE_ID = 'AgACAgIAAxkBAAIEJ2nFbBEG2KEbmvAZBHnUyhmR_rkTAAJnF2sbJ2kpSjaONzADaff8AQADAgADeAADOgQ'
MAIN_MENU_IMAGE_FILE_ID = 'AgACAgIAAxkBAAILumnWAv0c6uSQOECSBFlaA7bPvM4jAALoFWsb43OwSmaQzA3VTpunAQADAgADeAADOwQ'
CHAT_IMAGE_FILE_ID = 'AgACAgIAAxkBAAIJnWnQ-JBXOcuFwF3Zq87JLp8WKwduAAK6EWsbHmaISk1tUtGIyT_0AQADAgADeQADOwQ'
MY_PROFILES_DELETE_IMAGE_FILE_ID = 'AgACAgIAAxkBAAIJn2nQ-KtlWeNneRneeIRdrQJ7Iot3AAK7EWsbHmaISrY7okNvrGMcAQADAgADeQADOwQ'
ACTIVITY_IMAGE_FILE_ID = PROFILE_STATS_IMAGE_FILE_ID
ACTIVITY_SUBSCRIPTIONS_IMAGE_FILE_ID = PROFILE_NOTIFICATIONS_IMAGE_FILE_ID
ACTIVITY_SUBSCRIBERS_IMAGE_FILE_ID = PROFILE_NOTIFICATIONS_IMAGE_FILE_ID
ACTIVITY_LIKES_IMAGE_FILE_ID = PROFILE_STATS_IMAGE_FILE_ID
ACTIVITY_LIKED_BY_IMAGE_FILE_ID = PROFILE_STATS_IMAGE_FILE_ID
ACTIVITY_FRIENDS_IMAGE_FILE_ID = PROFILE_IMAGE_FILE_ID

__all__ = (
    'PROFILE_IMAGE_FILE_ID',
    'PROFILE_STATS_IMAGE_FILE_ID',
    'PROFILE_NOTIFICATIONS_IMAGE_FILE_ID',
    'PROFILE_LANGUAGE_IMAGE_FILE_ID',
    'SEARCH_GAME_PICK_IMAGE_FILE_ID',
    'PROFILE_EDIT_IMAGE_FILE_ID',
    'MY_PROFILES_IMAGE_FILE_ID',
    'MY_PROFILES_CREATE_IMAGE_FILE_ID',
    'MAIN_MENU_IMAGE_FILE_ID',
    'CHAT_IMAGE_FILE_ID',
    'MY_PROFILES_DELETE_IMAGE_FILE_ID',
    'ACTIVITY_IMAGE_FILE_ID',
    'ACTIVITY_SUBSCRIPTIONS_IMAGE_FILE_ID',
    'ACTIVITY_SUBSCRIBERS_IMAGE_FILE_ID',
    'ACTIVITY_LIKES_IMAGE_FILE_ID',
    'ACTIVITY_LIKED_BY_IMAGE_FILE_ID',
    'ACTIVITY_FRIENDS_IMAGE_FILE_ID',
)
